export const ON_START_ADD_CART = "ON_START_ADD_CART";
export const ON_SUCCESS_ADD_CART = "ON_SUCCESS_ADD_CART";
export const ON_FAILED_ADD_CART = "ON_FAILED_ADD_CART ";

export const ON_START_ADD_CART_DEC = "ON_START_ADD_CART_DEC";
export const ON_SUCCESS_ADD_CART_DEC = "ON_SUCCESS_ADD_CART_DEC";
export const ON_FAILED_ADD_CART_DEC = "ON_FAILED_ADD_CART_DEC ";

export const ON_START_ADD_CART_TOTAL_QUANTITY =
  "ON_START_ADD_CART_TOTAL_QUANTITY";
export const ON_FAILED_ADD_CART_TOTAL_QUANTITY =
  " ON_FAILED_ADD_CART_TOTAL_QUANTITY";
