export const ON_START_ADD_CART = "ON_START_ADD_CART";
export const ON_SUCCESS_ADD_CART = "ON_SUCCESS_ADD_CART";
export const ON_FAILED_ADD_CART = "ON_FAILED_ADD_CART ";

export const ON_START_ADD_CART_COUNT = "ON_START_ADD_CART_COUNT";
export const ON_SUCCESS_ADD_CART_COUNT = "ON_SUCCESS_ADD_CART_COUNT";
export const ON_FAILED_ADD_CART_COUNT = "ON_FAILED_ADD_CART_COUNT ";
