export const ON_FETCH_START_SINGLE_PRODUCT = "ON_FETCH_START_SINGLE_PRODUCT";
export const ON_FETCH_START_SINGLE_SUCCESS = "ON_FETCH_START_SINGLE_SUCCESS";
export const ON_FETCH_START_SINGLE_FAILED = "ON_FETCH_START_SINGLE_FAILED ";
